name: Validate .desktop file
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths:
      - qt/res/app.organicmaps.desktop.desktop
      - .github/workflows/desktop-file-check.yaml  # Run check on self change

jobs:
  validate-desktop-file:
    name: Validate .desktop file
    runs-on: docker
    container:
      image: linux-env
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            qt/res/app.organicmaps.desktop.desktop

      - name: Install desktop-file-validate tool
        shell: bash
        run: |
          apt update -y
          apt install -y \
              desktop-file-utils

      - name: Validate desktop file
        shell: bash
        run: desktop-file-validate qt/res/app.organicmaps.desktop.desktop && echo "Successfully validated .desktop file"
